---
# tasks file for ovirt-vm-create


## Create the VMs
# @action ovirt_auth # Obtain an SSO token
- name: Obtain SSO token
  ovirt_auth:
    username: "{{ ovirt_user_name }}"
    password: "{{ ovirt_user_password }}"
    state: present
    insecure: "{{ ovirt_insecure_login }}"
    url: "{{ ovirt_url_fqdn }}"

# @todo improvement:
# remove the forced naming of ovirt_name + ovirt_count

# @action ovirt_vm # Create the virtual machine on oVirt/RHV

- name: "Create {{ ovirt_name }}-{{ ovirt_count }}"
  ovirt_vm:
    state: running
    name: "{{ ovirt_name }}-{{ ovirt_count }}"
    template: "{{ ovirt_rhv_template }}"
    cluster: "{{ ovirt_cluster }}"
    cpu_cores: "{{ openshift_cpu_cores }}"
    memory: "{{ openshift_memory }}"
    wait: "{{ ovirt_wait }}"
    storage_domain: "{{ ovirt_vm_disk_storage_domain }}"
    cloud_init:
      host_name: "{{ ovirt_name }}-{{ ovirt_count }}.{{ ovirt_domain_name }}"
      dns_search: "{{ ovirt_dns_search }}"
      nic_boot_protocol: "{{ ovirt_nic_boot_protocol }}"
      nic_ip_address: "{{ ovirt_nic_ip_address }}"
      nic_netmask: "{{ ovirt_nic_netmask }}"
      nic_gateway: "{{ ovirt_nic_gateway }}"
      nic_name: "{{ ovirt_nic_name }}"
      nic_on_boot: "{{ ovirt_nic_on_boot }}"
