---
# tasks file for ovirt-vm-create

## Create the VMs
- name: Obtain SSO token
  ovirt_auth:

- name: "Create VM"
  ovirt_vm:
    state: running
    name: "{{ ovirt_name }}-{{ ovirt_count }}"
    template: "{{ ovirt_rhv_template }}"
    cluster: "{{ ovirt_cluster }}"
    cpu_cores: "{{ openshift_cpu_cores }}"
    memory: "{{ openshift_memory }}"
    wait: "{{ ovirt_wait }}"
    storage_domain: "{{ ovirt_vm_disk_storage_domain }}"
    cloud_init:
      host_name: "{{ ovirt_name }}-{{ ovirt_count }}.{{ ovirt_domain_name }}"
      dns_search: "{{ ovirt_dns_search }}"
      nic_boot_protocol: "{{ ovirt_nic_boot_protocol }}"
      nic_ip_address: "{{ ovirt_nic_ip_address }}"
      nic_netmask: "{{ ovirt_nic_netmask }}"
      nic_gateway: "{{ ovirt_nic_gateway }}"
      nic_name: "{{ ovirt_nic_name }}"
      nic_on_boot: "{{ ovirt_nic_on_boot }}"
